FROM node:20-slim as build

WORKDIR /app

COPY package.json .
COPY yarn.lock .
COPY ./orderly-dashboard-FE/ .
RUN yarn && \
    yarn build

FROM build

WORKDIR /app/orderly-dashboard-FE

COPY package.json /app
COPY yarn.lock /app
COPY ./orderly-dashboard-FE/package.json /app
COPY ./orderly-dashboard-FE/build /app
COPY --from=build /app/build .
RUN yarn --prod

ENV QUERY_SERVICE_URL=https://orderly-dashboard-query-service.orderly.network
ENV EVM_API_URL=https://api-evm.orderly.org

EXPOSE 3000

CMD ["yarn", "start"]
