# syntax=docker/dockerfile-upstream:experimental

FROM ubuntu:22.04 as build
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN apt update && apt install -y git cmake g++ pkg-config libssl-dev curl llvm clang libpq-dev ca-certificates && rm -rf /var/lib/apt/lists/*

# set HOME env variable of root user
ENV HOME=/root
WORKDIR ${HOME}/orderly
ADD . .

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --no-modify-path
ENV PATH=${HOME}/.cargo/bin:${PATH}

RUN echo "[net]\ngit-fetch-with-cli = true" > ${HOME}/.cargo/config

ENV RUSTFLAGS="-C target-cpu=x86-64"
ENV PORTABLE=ON

RUN cargo test --release -p orderly-dashboard-analyzer
RUN cargo build --release -p orderly-dashboard-analyzer

RUN cargo install diesel_cli --git https://github.com/diesel-rs/diesel.git --tag v2.2.6 --no-default-features --features "postgres" --bin diesel

FROM ubuntu:22.04 as execution
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC

RUN apt update && apt install -y libssl-dev libpq-dev ca-certificates && rm -rf /var/lib/apt/lists/*

COPY --from=build /root/orderly/target/release/orderly-dashboard-analyzer /usr/local/bin/orderly-dashboard-analyzer
COPY --from=build /root/.cargo/bin/diesel /usr/local/bin/diesel

ENV HOME=/home/orderly
WORKDIR ${HOME}

COPY ./orderly-dashboard-analyzer/migrations ./migrations

RUN echo '#!/usr/bin/env bash \n'\
    'set -euo pipefail \n'\
    'diesel migration run \n'\
    'RUST_BACKTRACE=1 orderly-dashboard-analyzer -c config.json ${1+"${@}"} \n' > ./entrypoint.sh

RUN chmod 755 ./entrypoint.sh

EXPOSE 8019

ENTRYPOINT [ "./entrypoint.sh" ]
