FROM node:20-slim as build

WORKDIR /app

COPY package.json .
COPY yarn.lock .
COPY ./orderly-dashboard-FE/ .
RUN yarn && \
    yarn build

FROM build

WORKDIR /app/orderly-dashboard-FE

COPY package.json /app
COPY yarn.lock /app
COPY ./orderly-dashboard-FE/package.json /app
COPY --from=build /app/build .
RUN yarn --prod

EXPOSE 3000

CMD ["yarn", "start"]
