// AUTO-GENERATED by typescript-type-def

export default types;
export namespace types {
    export type F64 = number;
    export type DailyVolumeExtern = {
        "daytime": (string)[];
        "volume": (types.F64)[];
    };
    export type DailyTradingFeeExtern = {
        "daytime": (string)[];
        "fee_amount": (types.F64)[];
    };
    export type TradingVolumeRanking = {
        "account_ids": (string)[];
        "volume": (types.F64)[];
    };
    export type TradingPnlRanking = {
        "account_ids": (string)[];
        "volume": (types.F64)[];
    };
    export type TokenAmountRanking = {
        "account_ids": (string)[];
        "volume": (types.F64)[];
    };
    export type OrderlyPerpDaily = {
        "trading_volume": types.F64;
        "trading_fee": types.F64;
        "trading_count": types.F64;
        "trading_user_count": types.F64;
        "liquidation_amount": types.F64;
        "liquidation_count": types.F64;
        "opening_count": types.F64;
    };
    export type DailyData<T> = {
        "daytime": (string)[];
        "data": (T)[];
    };
    export type OrderlyGasFee = {
        "avg_gas_fee": types.F64;
    };
    export type OrderlyTokenDaily = {
        "withdraw_amount": types.F64;
        "withdraw_count": types.F64;
        "deposit_amount": types.F64;
        "deposit_count": types.F64;
    };
    export type UserPerpHoldingRanking = {
        "account_ids": (string)[];
        "holding": (types.F64)[];
    };
    export type CountAverageExtern = {
        "latest_day_metric": types.F64;
        "latest_week_metric": types.F64;
        "latest_month_metric": types.F64;
    };
}
